id: I49C03DFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T19:21:33+00:00'
last_modified: '2022-06-09T04:34:08.196624+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ15298
  title: ཕྱག་ཆེན་ཟླ་བའི་འོད་ཟེར་དང་གསང་སྔགས་སྤྱི་དོན་ནོར་བུའི་འོད་ཟེར་བཅས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3634':
      image_group_id: I1KG12824
      title: Volume 1 of phyag rgya chen po'i sgom rim gsal bar byed pa'i legs bshad
        zla ba'i 'od zer sogs/
      total_pages: 528
      order: 1
      base_file: 3634.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
