id: P007072
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ15298
  title: ཕྱག་ཆེན་ཟླ་བའི་འོད་ཟེར་དང་གསང་སྔགས་སྤྱི་དོན་ནོར་བུའི་འོད་ཟེར་བཅས།
  author: ''
  volumes:
    371e0d5527534e028ab1aed85695f0ff:
      image_group_id: I1KG12824
      title: ''
      volume_number: 1
      total_pages: 528
ebook_metadata:
  title: ཕྱག་ཆེན་ཟླ་བའི་འོད་ཟེར་དང་གསང་སྔགས་སྤྱི་དོན་ནོར་བུའི་འོད་ཟེར་བཅས།
  author: ''
  sku: P007072
  cover: cover.jpg
  layers:
  - pagination
